name: Build Windows Zip

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction --no-ansi

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --name DocChatbot main.py

      - name: Create release zip
        run: |
          python tools/package_release.py

      - name: Upload artifact\n        uses: actions/upload-artifact@v4\n        with:\n          name: DocChatbot-win64\n          path: DocChatbot-win64.zip\n\n      - name: Create GitHub Release\n        if: startsWith(github.ref, 'refs/tags/')\n        uses: softprops/action-gh-release@v2\n        with:\n          files: |\n            DocChatbot-win64.zip\n
