name: build-windows-exe

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Configure Poetry (no venv)
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build EXE with PyInstaller (spec)
        run: pyinstaller --noconfirm DocChatbot.spec

      - name: Prepare dist extras
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path dist\docs -Force | Out-Null
          if (Test-Path docs) { robocopy docs dist\docs /E | Out-Null }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocChatbot-win
          path: |
            dist/DocChatbot.exe
            dist/api_key.txt
            dist/docs/**

      - name: Zip distribution for release
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          Compress-Archive -Path dist\DocChatbot.exe -DestinationPath dist\DocChatbot-win.zip -Force

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/DocChatbot.exe
            dist/DocChatbot-win.zip
